### PR TITLE
Create initial flask project

### PR DESCRIPTION
**Pull request by GitauHarrison**
@pereruannabaala 

I have added a Flask project structure to the existing files; I have yet to update them to Flask. 

See the `README.md` of [V1.0.1](https://github.com/GitauHarrison/ShopOnline/releases/tag/V1.0.1) for more info.

Curious how you can read the `README.md` file? 

see_readme

### CODE REVIEW

**Comment by pereruannabaala** [comment]
Sawa sawa. I’ll check them out tomorrow.

Good night.

**Comment by GitauHarrison** [comment]
@pereruannabaala check the `README.md` section to see how you can run this project locally. Let me know if you can locally view the project in your browser.

**Comment by GitauHarrison** [comment]
@pereruannabaala push the new template for your select dashboard so I can view it

**Comment by pereruannabaala** [comment]
hi H, cal today ? Sorry I've been busy plus my phone is spoilt so please
text me on here

**Pull request merged**
